
namespace Database.SouthAfricanCensus.CSVs
{
	public class CSVRow2011Household : CSVRow2011
	{
        public CSVRow2011Household(string line) : base(line) { }

        "QN_TYPE","SN","H01_QUARTERS","H02_MAINDWELLING","H02_OTHERDWELLING","H02A_ROOF","H02A_WALL","H03_DININGROOMS","H03_LIVINGROOMS","H03_DINING_LIVING","H03_BEDROOMS","H03_STUDYROOMS","H03_MULTIPLE_USE","H03_OTHERROOMS","H03_TOTROOMS","H04_TENURE","H07_WATERPIPED","H08_WATERSOURCE","H09_WATERSUPPLY","H09A_WATERSUPPLY","H09B_ALT_WATERSOURCE","H10_TOILET","H11_ENERGY_COOKING","H11_ENERGY_HEATING","H11_ENERGY_LIGHTING","H12_REFUSE","H13_REFRIDGERATOR","H13_STOVE","H13_VACUUM","H13_WASHINGM","H13_COMPUTER","H13_SATELLITE","H13_DVD_PLAYER","H13_MOTORCAR","H13_TV","H13_RADIO","H13_LANDLINE","H13_CELLPHONE","H13_POSTBOX","H13_RESIDENTIAL_MAIL","H13A_INTERNET","HM00_DEATHS","HM00A_DEATHSNO","DERH_HHAGE","DERH_HHPOP","DERH_HHSEX","DERH_HINCOME","DERH_HH_EMPLOY_STATUS","DERH_HSIZE","DERH_XPOP","DERH_INCOME_CLASS","H_GEOTYPE","H_PROVINCE","H_DISTRICT","H_MUNIC","HHLD_10PERCENT_WGT"
    }
}